---
# Shell aliases and functions
- name: Create shell aliases file
  copy:
    dest: "{{ user_home }}/.shell_aliases"
    content: |
      # Common aliases
      alias ll='ls -alF'
      alias la='ls -A'
      alias l='ls -CF'
      alias grep='grep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias egrep='egrep --color=auto'
      
      # Modern replacements
      alias cat='bat'
      alias ls='eza'
      alias find='fd'
    mode: '0644'

- name: Source aliases in shell rc files
  lineinfile:
    path: "{{ item }}"
    line: "source ~/.shell_aliases"
    create: yes
  loop:
    - "{{ user_home }}/.bashrc"

- name: Create Fish shell aliases
  copy:
    dest: "{{ user_home }}/.config/fish/config.fish"
    content: |
      # Fish shell configuration
      
      # Common aliases  
      alias ll='ls -alF'
      alias la='ls -A'
      alias l='ls -CF'
      alias grep='grep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias egrep='egrep --color=auto'
      
      # Modern replacements
      alias cat='bat'
      alias ls='eza'
      alias find='fd'
      
      # Fish-specific settings
      set -g fish_greeting ""
    mode: '0644'
  when: package_state == 'present'