---
# General shell packages and setup
- name: Install shell packages
  package:
    name: "{{ shell_packages }}"
    state: present
  become: true

- name: Install additional shell tools
  package:
    name:
      - fzf
      - ripgrep
      - bat
      - fd-find
      - eza
    state: present
  become: true