---
# General shell packages and setup
- name: Install/Remove shell packages
  package:
    name: "{{ shell_packages }}"
    state: "{{ package_state }}"
  become: true

- name: Install/Remove additional shell tools
  package:
    name:
      - fzf
      - ripgrep
      - bat
      - fd-find
      - eza
    state: "{{ package_state }}"
  become: true