---
# Tmux configuration
- name: Create tmux config directory
  file:
    path: "{{ user_home }}/.config/tmux"
    state: directory
    mode: '0755'

# Tmux configuration template removed - add manually if needed
# Template was referencing non-existent tmux.conf.j2