---
# Zsh configuration and setup
- name: Set zsh as default shell
  user:
    name: "{{ user_name }}"
    shell: "{{ shell_config.default_shell }}"
  become: true
  when: shell_config.default_shell is defined

# Oh My Zsh and other zsh frameworks can be installed as needed