---
# Zsh configuration and setup
- name: Set zsh as default shell
  user:
    name: "{{ user_name }}"
    shell: "{{ shell_config.default_shell }}"
  become: true
  when: shell_config.default_shell is defined

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ user_home }}/.oh-my-zsh"
  become_user: "{{ user_name }}"