---
# GNOME dock management

- name: Define dock applications
  set_fact:
    dock_favorites:
      - chromium.desktop
      - slack.desktop
      - com.raggesilver.BlackBox.desktop
      - code.desktop

- name: Configure GNOME dock favorites
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "{{ dock_favorites }}"
    state: "{{ 'present' if package_state == 'present' else 'absent' }}"
  become_user: "{{ user_name }}"

- name: Configure dash-to-dock settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: "{{ 'present' if package_state == 'present' else 'absent' }}"
  become_user: "{{ user_name }}"
  loop:
    - { key: "/org/gnome/shell/extensions/dash-to-dock/show-mounts", value: "true" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/show-trash", value: "true" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/extend-height", value: "true" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed", value: "false" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/multi-monitor", value: "true" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size", value: "48" }