---
# Git configuration and setup
- name: Configure git user name
  git_config:
    name: user.name
    value: "{{ git_config.user_name }}"
    scope: global
  when: git_config.user_name is defined and git_config.user_name != ""

- name: Configure git user email
  git_config:
    name: user.email
    value: "{{ git_config.user_email }}"
    scope: global
  when: git_config.user_email is defined and git_config.user_email != ""

- name: Configure git signing key
  git_config:
    name: user.signingkey
    value: "{{ git_config.signing_key }}"
    scope: global
  when: git_config.signing_key is defined and git_config.signing_key != ""

- name: Enable commit signing by default
  git_config:
    name: commit.gpgsign
    value: "true"
    scope: global
  when: git_config.signing_key is defined and git_config.signing_key != ""