---
# Core system setup tasks
- name: Install core packages
  package:
    name: "{{ core_packages }}"
    state: present
  become: true

- name: Ensure user directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ dev_dir }}"
    - "{{ bin_dir }}"
    - "{{ config_dir }}"