---
# SSH configuration and key management
- name: Ensure .ssh directory exists
  file:
    path: "{{ user_home }}/.ssh"
    state: directory
    mode: '0700'

# SSH keys are expected to already exist - no generation needed
  
- name: Configure SSH for GitHub
  blockinfile:
    path: "{{ user_home }}/.ssh/config"
    create: yes
    mode: '0600'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - GitHub"
    block: |
      Host github.com
        HostName github.com
        User git
        IdentityFile ~/.ssh/github_id_rsa