---
# SSH configuration and key management
- name: Ensure .ssh directory exists
  file:
    path: "{{ user_home }}/.ssh"
    state: directory
    mode: '0700'

- name: Deploy SSH private key for GitHub
  copy:
    content: "{{ ssh_keys.github_private_key }}"
    dest: "{{ user_home }}/.ssh/github_id_rsa"
    mode: '0600'
  when: ssh_keys.github_private_key is defined
  no_log: true

- name: Generate SSH public key from private key
  shell: ssh-keygen -y -f "{{ user_home }}/.ssh/github_id_rsa" > "{{ user_home }}/.ssh/github_id_rsa.pub"
  when: ssh_keys.github_private_key is defined
  
- name: Configure SSH for GitHub
  blockinfile:
    path: "{{ user_home }}/.ssh/config"
    create: yes
    mode: '0600'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - GitHub"
    block: |
      Host github.com
        HostName github.com
        User git
        IdentityFile ~/.ssh/github_id_rsa