# Configuration settings
git_config:
  user_name: "bashfulrobot"
  user_email: "dustin@bashfulrobot.com"
  
shell_config:
  default_shell: "/bin/zsh"

dev_config:
  editor: "hx"

# State management - set to 'absent' to remove instead of install
package_state: "present"
service_state: "started"
config_state: "present"