---
# Sys suite - orchestrates all system configuration
- name: Sys - General system packages
  include_tasks: general.yml

- name: Sys - Network configuration
  include_tasks: network.yml

- name: Sys - Security hardening
  include_tasks: security.yml

- name: Sys - Performance tuning
  include_tasks: performance.yml