---
# Docker development setup
- name: Install Docker
  package:
    name:
      - docker.io
      - docker-compose
    state: present
  become: true

- name: Add user to docker group
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes
  become: true

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: true