---
# Node.js development setup
- name: Install Node.js and npm
  package:
    name:
      - nodejs
      - npm
    state: present
  become: true

- name: Install global npm packages
  npm:
    name: "{{ item }}"
    global: yes
  loop:
    - yarn
    - typescript
    - "@typescript-eslint/parser"
    - "@typescript-eslint/eslint-plugin"
    - eslint
    - prettier
  become: true