---
# Node.js development setup
- name: Install/Remove Node.js and npm
  package:
    name:
      - nodejs
      - npm
    state: "{{ package_state }}"
  become: true

- name: Install/Remove global npm packages
  npm:
    name: "{{ item }}"
    state: "{{ package_state }}"
    global: yes
  loop:
    - "@anthropic-ai/claude-code"
  become: true
  when: package_state == 'present'