---
# Node.js development setup
- name: Install Node.js and npm
  package:
    name:
      - nodejs
      - npm
    state: present
  become: true

- name: Install global npm packages
  npm:
    name: "{{ item }}"
    global: yes
  loop:
    - "@anthropic-ai/claude-code"
  become: true