---
# Python development setup
- name: Install Python development packages
  package:
    name:
      - python3-pip
      - python3-venv
      - python3-dev
      - pipx
    state: present
  become: true

# Python development tools can be installed as needed per project