---
# Python development setup
- name: Install Python development packages
  package:
    name:
      - python3-pip
      - python3-venv
      - python3-dev
      - pipx
    state: present
  become: true

- name: Install common Python development tools via pipx
  pipx:
    name: "{{ item }}"
  loop:
    - black
    - flake8
    - mypy
    - pytest
    - poetry
  become_user: "{{ user_name }}"