---
- name: Configure laptop
  hosts: localhost
  become: false
  gather_facts: true

  vars_files:
    - ../vars/packages.yml
    - ../vars/configs.yml
    - ../vars/secrets.yml

  pre_tasks:
    - name: Remove conflicting nodesource repository file
      file:
        path: /etc/apt/sources.list.d/nodesource.list
        state: absent
      become: true

  roles:
    - role: core
      tags: core
    - role: sys
      tags: sys
    - role: shell
      tags: shell
    - role: dev
      tags: dev
    - role: infra
      tags: infra
    - role: offcoms
      tags: offcoms