---
# 1Password installation

- name: Check if 1Password is already installed
  command: dpkg -l 1password
  register: onepassword_check
  failed_when: false
  changed_when: false

- name: 1Password installation block
  block:
    - name: Add the key for the 1Password apt repository
      shell: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/1password-archive-keyring.gpg
      become: true

    - name: Add the 1Password apt repository
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main'
        state: present
        filename: 1password
      become: true

    - name: Add the debsig-verify policy directory
      file:
        path: /etc/debsig/policies/AC2D62742012EA22/
        state: directory
        mode: '0755'
      become: true

    - name: Add the debsig-verify policy file
      get_url:
        url: https://downloads.1password.com/linux/debian/debsig/1password.pol
        dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
        mode: '0644'
      become: true

    - name: Create debsig keyring directory
      file:
        path: /usr/share/debsig/keyrings/AC2D62742012EA22
        state: directory
        mode: '0755'
      become: true

    - name: Add the debsig-verify GPG key
      shell: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
      args:
        creates: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
      become: true

    - name: Install 1Password and 1Password CLI
      apt:
        name:
          - 1password
          - 1password-cli
        state: present
        update_cache: yes
      become: true

  when:
    - package_state == 'present'
    - onepassword_check.rc != 0

- name: Remove 1Password
  block:
    - name: Remove 1Password and 1Password CLI
      apt:
        name:
          - 1password
          - 1password-cli
        state: absent
      become: true

    - name: Remove 1Password apt repository
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main'
        state: absent
        filename: 1password
      become: true

    - name: Remove 1Password GPG key
      file:
        path: /usr/share/keyrings/1password-archive-keyring.gpg
        state: absent
      become: true

    - name: Remove debsig-verify policy and keyring
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/debsig/policies/AC2D62742012EA22
        - /usr/share/debsig/keyrings/AC2D62742012EA22
      become: true

  when: package_state == 'absent'
