---
# Chromium installation via XtraDeb PPA for Ubuntu 24.04
# Following instructions from https://ubuntuhandbook.org/index.php/2024/05/install-chromium-ubuntu-2404/

- name: Check if Chromium is already installed
  command: dpkg -l chromium
  register: chromium_check
  failed_when: false
  changed_when: false

- name: Chromium installation block
  block:
    - name: Install prerequisites for repository
      package:
        name:
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present
      become: true

    - name: Add XtraDeb PPA for Chromium
      shell: add-apt-repository -y ppa:xtradeb/apps
      become: true
      register: ppa_result

    - name: Debug PPA addition result
      debug:
        var: ppa_result
      when: ppa_result is defined

    - name: Update apt cache after adding PPA
      apt:
        update_cache: yes
      become: true
      register: cache_update_result

    - name: Debug cache update result
      debug:
        var: cache_update_result
      when: cache_update_result is defined

    - name: Install Chromium
      package:
        name: chromium
        state: present
      become: true

  when: 
    - package_state == 'present'
    - chromium_check.rc != 0

- name: Configure Chromium extensions
  include_tasks: chromium-extensions.yml

- name: Remove Chromium and PPA
  block:
    - name: Remove Chromium package
      package:
        name: chromium
        state: absent
      become: true

    - name: Remove XtraDeb PPA
      shell: add-apt-repository -y --remove ppa:xtradeb/apps
      become: true
      failed_when: false

    - name: Update apt cache after removing repository
      apt:
        update_cache: yes
      become: true

  when: package_state == 'absent'

- name: Verify Chromium installation
  command: chromium --version
  register: chromium_version
  failed_when: false
  changed_when: false
  when: package_state == 'present'

- name: Display Chromium version
  debug:
    msg: "{{ chromium_version.stdout }}"
  when: 
    - package_state == 'present'
    - chromium_version.rc == 0