---
# Slack installation from official deb package
- name: Create temporary directory for Slack installation
  tempfile:
    state: directory
    suffix: slack
  register: slack_temp_dir

- name: Download Slack deb package (latest)
  get_url:
    url: "https://slack.com/downloads/instructions/linux?ddl=1&build=deb"
    dest: "{{ slack_temp_dir.path }}/slack-desktop-amd64.deb"
    mode: '0644'
    follow_redirects: yes
    timeout: 30
  register: slack_download
  tags: 
    - downloads
    - slow
    - never

- name: Install Slack deb package with dpkg
  command: dpkg -i "{{ slack_download.dest }}"
  become: yes
  register: dpkg_result
  failed_when: false
  when: not slack_download is skipped
  tags: 
    - downloads
    - slow
    - never

- name: Fix broken dependencies if dpkg installation failed
  apt:
    update_cache: yes
    fix_broken: yes
  become: yes
  when: 
    - not slack_download is skipped
    - dpkg_result.rc != 0
  tags: 
    - downloads
    - slow
    - never

- name: Verify Slack installation
  command: dpkg -l slack-desktop
  register: slack_verify
  failed_when: false
  changed_when: false
  when: not slack_download is skipped
  tags: 
    - downloads
    - slow
    - never

- name: Clean up temporary directory
  file:
    path: "{{ slack_temp_dir.path }}"
    state: absent
  when: slack_temp_dir.path is defined