---
# Slack installation using known working direct URL 
- name: Check if Slack is already installed
  command: dpkg -l slack-desktop
  register: slack_check
  failed_when: false
  changed_when: false

- name: DEBUG - Log Slack check result
  debug:
    msg: "Slack check result: rc={{ slack_check.rc }}, package_state={{ package_state }}"

- name: Slack installation block
  block:
    - name: Create temporary directory for Slack installation
      tempfile:
        state: directory
        suffix: slack
      register: slack_temp_dir

    - name: Scrape Slack downloads page to get version number
      command: >
        curl -s -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        "https://slack.com/intl/en-gb/downloads/linux"
      register: slack_page_html
      tags:
        - downloads
        - slow
        - never

    - name: Extract Slack version number from HTML
      set_fact:
        slack_version: "{{ slack_page_html.stdout | regex_search('Version ([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1') | first }}"
      tags:
        - downloads
        - slow
        - never

    - name: DEBUG - Log scraped Slack version
      debug:
        msg: "Scraped Slack version: {{ slack_version }}"
      tags:
        - downloads
        - slow
        - never

    - name: Construct direct download URL using scraped version
      set_fact:
        slack_download_url: "https://downloads.slack-edge.com/releases/linux/{{ slack_version }}/prod/x64/slack-desktop-{{ slack_version }}-amd64.deb"
      when: slack_version is defined and slack_version != ""
      tags:
        - downloads
        - slow
        - never

    - name: DEBUG - Log constructed download URL
      debug:
        msg: "Constructed Slack download URL: {{ slack_download_url }}"
      tags:
        - downloads
        - slow
        - never

    - name: Download Slack deb package from constructed URL
      get_url:
        url: "{{ slack_download_url }}"
        dest: "{{ slack_temp_dir.path }}/slack-desktop-amd64.deb"
        mode: '0644'
        timeout: 60
      register: slack_download
      when: slack_download_url is defined and slack_download_url != ""
      tags:
        - downloads
        - slow
        - never

    - name: DEBUG - Log download result
      debug:
        var: slack_download
      tags:
        - downloads
        - slow
        - never

    - name: Install Slack deb package with dpkg
      command: dpkg -i "{{ slack_download.dest }}"
      become: yes
      register: dpkg_result
      failed_when: false
      when: slack_download is defined and slack_download.dest is defined

    - name: DEBUG - Log dpkg result  
      debug:
        var: dpkg_result
      when: dpkg_result is defined

    - name: Fix broken dependencies if dpkg installation failed
      command: apt-get install -f -y
      become: yes
      register: apt_fix_result
      when: 
        - dpkg_result is defined
        - dpkg_result.rc != 0

    - name: Clean up temporary directory
      file:
        path: "{{ slack_temp_dir.path }}"
        state: absent
      when: slack_temp_dir.path is defined

  when: 
    - package_state == 'present'
    - slack_check.rc != 0

- name: Remove Slack
  apt:
    name: slack-desktop
    state: absent
  become: yes
  when: package_state == 'absent'

- name: Verify Slack installation
  command: dpkg -l slack-desktop
  register: slack_verify
  failed_when: false
  changed_when: false
  when: package_state == 'present'

- name: DEBUG - Log final verification
  debug:
    var: slack_verify
  when: package_state == 'present'