---
# Slack installation via official method - dynamically get latest version
- name: Check if Slack is already installed
  command: dpkg -l slack-desktop
  register: slack_check
  failed_when: false
  changed_when: false

- name: Slack installation block
  block:
    - name: Create keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      become: yes

    - name: Download Slack GPG key
      get_url:
        url: "https://packagecloud.io/slacktechnologies/slack/gpgkey"
        dest: "/etc/apt/keyrings/slack.asc"
        mode: '0644'
      become: yes
      tags:
        - downloads
        - slow  
        - never

    - name: Add Slack repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/slack.asc] https://packagecloud.io/slacktechnologies/slack/ubuntu/ {{ ansible_distribution_release }} main"
        state: present
      become: yes
      when: package_state == 'present'
      tags:
        - downloads
        - slow
        - never

    - name: Install Slack from repository
      apt:
        name: slack-desktop
        state: present
        update_cache: yes
      become: yes
      when: package_state == 'present'

  when: 
    - package_state == 'present'
    - slack_check.rc != 0

- name: Remove Slack
  apt:
    name: slack-desktop
    state: absent
  become: yes
  when: package_state == 'absent'

- name: Remove Slack repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/slack.asc] https://packagecloud.io/slacktechnologies/slack/ubuntu/ {{ ansible_distribution_release }} main"
    state: absent
  become: yes
  when: package_state == 'absent'

- name: Verify Slack installation
  command: dpkg -l slack-desktop
  register: slack_verify
  failed_when: false
  changed_when: false
  when: package_state == 'present'