---
# Slack installation by following redirect to get actual download URL
- name: Check if Slack is already installed
  command: dpkg -l slack-desktop
  register: slack_check
  failed_when: false
  changed_when: false

- name: Slack installation block
  block:
    - name: Create temporary directory for Slack installation
      tempfile:
        state: directory
        suffix: slack
      register: slack_temp_dir

    - name: Download Slack deb package (handles redirects automatically)  
      get_url:
        url: "https://slack.com/downloads/instructions/linux?ddl=1&build=deb"
        dest: "{{ slack_temp_dir.path }}/slack-desktop-amd64.deb"
        mode: '0644'
        timeout: 60
      register: slack_download
      tags:
        - downloads
        - slow
        - never

    - name: Install Slack deb package with dpkg
      command: dpkg -i "{{ slack_download.dest }}"
      become: yes
      register: dpkg_result
      failed_when: false

    - name: Fix broken dependencies if dpkg installation failed
      apt:
        update_cache: yes
        fix_broken: yes
      become: yes
      when: dpkg_result.rc != 0

    - name: Clean up temporary directory
      file:
        path: "{{ slack_temp_dir.path }}"
        state: absent
      when: slack_temp_dir.path is defined

  when: 
    - package_state == 'present'
    - slack_check.rc != 0

- name: Remove Slack
  apt:
    name: slack-desktop
    state: absent
  become: yes
  when: package_state == 'absent'

- name: Verify Slack installation
  command: dpkg -l slack-desktop
  register: slack_verify
  failed_when: false
  changed_when: false
  when: package_state == 'present'