---
# Slack installation via snap (most reliable method)
- name: Check if Slack snap is already installed
  command: snap list slack
  register: slack_snap_check
  failed_when: false
  changed_when: false

- name: DEBUG - Log Slack snap check result
  debug:
    msg: "Slack snap check result: rc={{ slack_snap_check.rc }}, package_state={{ package_state }}"

- name: Install Slack via snap
  snap:
    name: slack
    classic: yes
    state: present
  become: yes
  when: 
    - package_state == 'present'
    - slack_snap_check.rc != 0
  tags:
    - downloads
    - slow
    - never

- name: Remove Slack snap
  snap:
    name: slack
    state: absent
  become: yes
  when: package_state == 'absent'

- name: Verify Slack installation
  command: snap list slack
  register: slack_verify
  failed_when: false
  changed_when: false
  when: package_state == 'present'

- name: DEBUG - Log final verification
  debug:
    var: slack_verify
  when: package_state == 'present'